// RHS United States Armed Forces Arsenal Preset

// Mods needed:
// RHS USAF

GRLIB_arsenal_weapons = [
	"fow_w_type10",
	"fow_w_type100",
	"fow_w_type14",
	"fow_w_type77_mg",
	"fow_w_type77_mg_1",
	"fow_w_type77_mg_2",
	"fow_w_type77a_mg_2x",
	"fow_w_type92",
	"fow_w_type97_mortar",
	"fow_w_type99",
	"fow_w_type99_cannon_2x",
	"fow_w_type99_lmg",
	"fow_w_type99_sniper",
	"LIB_PTRD"
];

GRLIB_arsenal_magazines = [

];

GRLIB_arsenal_items = [
	"SmokeShell",
	"fow_v_ija_bayonet",
	"fow_v_ija_grenadier",
	"fow_v_ija_medic",
	"fow_v_ija_mg",
	"fow_v_ija_mortar",
	"fow_v_ija_nco",
	"fow_v_ija_officer",
	"fow_v_ija_rifle",
	"fow_i_fak_ija",
	"fow_e_tnt_halfpound",
	"fow_e_tnt_onepound_mag",
	"fow_e_tnt_twohalfpound_mag",
	"fow_e_tnt_twopound_mag",
	"ACE_fieldDressing",
	"ACE_elasticBandage",
	"ACE_quikclot",
	"ACE_LIB_FireCord",
	"ACE_bloodIV",
	"ACE_bloodIV_250",
	"ACE_bloodIV_500",
	"ACE_bodyBag",
	"ACE_DefusalKit",
	"ACE_LIB_LadungPM",
	"ACE_EarPlugs",
	"ACE_EntrenchingTool",
	"ACE_epinephrine",
	"ACE_Fortify",
	"ACE_morphine",
	"ACE_packingBandage",
	"ACE_personalAidKit",
	"ACE_salineIV",
	"ACE_salineIV_250",
	"ACE_salineIV_500",
	"fow_i_whistle",
	"ACE_tourniquet",
	"ACE_CableTie",
	"ItemCompass",
	"ItemMap",
	"ItemRadio",
	"ItemWatch",
	"Medikit",
	"MineDetector",
	"FirstAidKit",
	"Binocular",
	"ToolKit",
	"fow_u_ija_pilot",
	"fow_u_ija_type98",
	"fow_u_ija_type98_foliage",
	"fow_u_ija_type98_khakibrown",
	"fow_u_ija_type98_short",
	"fow_u_ija_type98_snlf",
	"fow_h_ija_fieldcap",
	"fow_h_ija_fieldcap_marine",
	"fow_h_ija_fieldcap_marine_neck",
	"fow_h_ija_fieldcap_neck",
	"fow_h_ija_fieldcap_officer",
	"fow_h_ija_flight_helmet",
	"fow_h_ija_hakimachi",
	"fow_h_ija_tank_helmet",
	"fow_h_ija_type90",
	"fow_h_ija_type90_foliage",
	"fow_h_ija_type90_net",
	"fow_h_ija_type90_net_neck",
	"fow_h_ija_type90_snlf"
];

GRLIB_arsenal_backpacks = [
	"fow_b_ija_ammobox",
	"fow_b_ija_ammobox_metal",
	"fow_b_ija_ammobox_wood",
	"fow_b_ija_backpack",
	"fow_b_ija_backpack_asst_type99",
	"fow_b_ija_backpack_foliage",
	"fow_b_ija_backpack_foliage_asst_type99",
	"fow_b_ija_backpack_foliage_medic",
	"fow_b_ija_backpack_foliage_rifleman",
	"fow_b_ija_backpack_medic",
	"fow_b_ija_backpack_rifleman",
	"fow_b_ija_type97_mortar_adv_weapon",
	"fow_b_ija_type97_mortar_support",
	"fow_b_ija_type97_mortar_weapon"
];